[platformio]
src_dir = .

[env:m5cardputer]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=2 #{Non,Err,Wrn,Inf,Dbg,Ver}
lib_deps = 
	m5stack/M5GFX
	m5stack/M5Unified
	m5stack/M5Cardputer
	m5stack/M5-DLight
